name: Exercício Lógica de programação (Expressões aritméticas)
type: dart
steps:
  - name: Step 1
    directory: step_01
    has_solution: true
  - name: Step 2
    directory: step_02
    has_solution: true